name: Terraform CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:

  terraform-init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: codes-terraform


  terraform-plan:
    needs: terraform-init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Plan
        run: terraform plan
        working-directory: codes-terraform


  terraform-apply:
    needs: terraform-plan
    if: github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: codes-terraform


  terraform-destroy:
    needs: terraform-plan
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: codes-terraform
      
        
