name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:

  terraform-init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: codes-terraform

      - name: Upload Terraform Folder
        uses: actions/upload-artifact@v4
        with:
          name: terraform-files
          path: codes-terraform


  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Download Terraform Files
        uses: actions/download-artifact@v4
        with:
          name: terraform-files
          path: codes-terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: codes-terraform

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: codes-terraform/tfplan


  terraform-apply-destroy:
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: codes-terraform

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan
        working-directory: codes-terraform

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: codes-terraform
